package com.network.rpcprotocol;

public enum ResponseType {
    OK, ERROR, REGISTERED_PARTICIPANT, ADDED_RACE, ADDED_USER, SEARCHED_BY_TEAM, USER_LOGGED_IN, USER_LOGGED_OUT, HASH_PASSWORD, IS_PARTICIPANT_REGISTERED_FOR_RACE, GET_NEXT_PARTICIPANT_ID, FIND_BY_NAME_AND_TEAM, FIND_AFTER_USERNAME, COUNT_REGISTRATIONS_FOR_RACE, GET_CAPACITY_FOR_PARTICIPANT, FIND_PARTICIPANT_BY_NAME_TEAM;
}
