package com.network.rpcprotocol;

public enum RequestType {
    LOGIN, LOGOUT, REGISTER_PARTICIPANT, ADD_RACE, ADD_USER, ADD_PARTICIPANT, GET_ALL_PARTICIPANTS, GET_ALL_RACES, FIND_BY_NAME_TEAM, COUNT_REGISTRATIONS_FOR_RACE, GET_CAPACITY_FOR_PARTICIPANT, FIND_AFTER_USERNAME, HASH_PASSWORD, GET_NEXT_PARTICIPANT_ID, IS_PARTICIPANT_REGISTERED_FOR_RACE, ADD_REGISTRATION, FIND_BY_NAME_AND_TEAM, FIND_PARTICIPANT_BY_NAME_TEAM, SEARCH_BY_TEAM
}
